### ISSUE TITLE
DCTL failed to run egdb.database test on release and debug configuration with MSVC on Windows

### ISSUE THREAD

**Issue by spacelg** [rhalbersma/dctl#29] opened 2019-12-26 06:23 UTC
DCTL failed to run egdb.database test on release and debug configuration with MSVC on Windows. It can be reproduced on  master branch latest reversion a63d2a3. Could you help take a look at this? Thanks a lot.

Repro steps:
1.  git clone https://github.com/rhalbersma/dctl.git D:\DCTL\src
2.  open a VS 2017 amd64 command prompt as admin and browse to D:\DCTL
3.  git clone https://github.com/rhalbersma/xstd.git D:\DCTL\xstd
4.  git clone https://github.com/rhalbersma/bit_set.git D:\DCTL\bit_set
5.  put boost_1_69_0 under C:\boost_1_69_0\x64
6.  cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 -DBOOST_ROOT=C:\boost_1_69_0\x64\boost -DBOOST_INCLUDEDIR=C:\boost_1_69_0\x64 ..\src\
7. msbuild /m /p:Configuration=Release;Platform=x64 dctl.sln /t:Rebuild
8.  ctest --build-config Release -E "egdb.divide|search|traversal"

[log_x64_test.log](https://github.com/rhalbersma/dctl/files/4001573/log_x64_test.log)

Failures:
      Start 35: egdb.database
35/37 Test #35: egdb.database ........................Exit code 0xc0000135
***Exception:   0.05 sec
      Start 36: egdb.index
36/37 Test #36: egdb.index ...........................   Passed    0.34 sec
      Start 37: util.literals
37/37 Test #37: util.literals ........................   Passed    0.05 sec

97% tests passed, 1 tests failed out of 37

Total Test time (real) =   2.87 sec

The following tests FAILED:
	 35 - egdb.database (Exit code 0xc0000135
)

**Comment by rhalbersma** [comment] 2019-12-26 10:10
Can you show the first few lines of the compilation? E.g. on AppVeyor I get this for VS 2017:

```
cmake .. -G "%GENERATOR_NAME%" -A %PLATFORM_NAME% "-DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake"
-- The CXX compiler identification is MSVC 19.16.27034.0
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Boost: C:/Tools/vcpkg/installed/x86-windows/include (found version "1.71.0") found components:  filesystem 
-- Found Boost: C:/Tools/vcpkg/installed/x86-windows/include (found version "1.71.0") found components:  unit_test_framework 
-- Configuring done
-- Generating done
-- Build files have been written to: C:/projects/dctl/build
cmake --build . --config %configuration%
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
```

In particular, on AppVeyor I cannot reproduce your build as VS 2017 errors out on tons of `constexpr` related bugs. The VS 2019 build job works correctly. Could you try with VS 2019?

**Comment by rhalbersma** [comment] 2019-12-26 10:26
I now added a `catch(...)` clause to catch all non-filesystem related exceptions. Could you run your compilation again please?

**Comment by spacelg** [comment] 2019-12-30 02:52
Hi rhalbersma,

Thanks for your reply!  

We mainly build open source projects to test the VS compiler. We use vs2017, but replace the vs2017 binary with the 2019 vs binary that has not yet been released. 

And now this issue still can be reproduced on latest version 991e87c, so I attached log_x64_cmake.log log_x64_build.log and log_x64_test.log for you.  Thanks a lot.

[log_x64_cmake.log](https://github.com/rhalbersma/dctl/files/4008865/log_x64_cmake.log)
[log_x64_build.log](https://github.com/rhalbersma/dctl/files/4008866/log_x64_build.log)
[log_x64_test.log](https://github.com/rhalbersma/dctl/files/4008867/log_x64_test.log)

Thanks,
Lin

**Comment by rhalbersma** [comment] 2019-12-30 08:10
Your build config uses Boost 1.69 and has 86 warnings from Boost.Hana. This is known to be a library with fragile Visual C++ support. In [my build using VS 2019 on AppVeyor](https://ci.appveyor.com/project/rhalbersma/dctl/build/job/wnpgga3gwneg22by), I use Boost 1.71 and get 0 warnings. I also suspect that the the 1.69 version of Boost.Filesystem is somehow not working correctly (although the `catch(...)` clause should catch all exceptions). Can you rebuild with the Boost version from `vcpkg`?

**Comment by rhalbersma** [comment] 2020-01-09 20:56
As I can't reproduce it, I'm closing this. Feel feel to re-open if you reproduce your errors with the AppVeyor build stack (VS 2019 16.4, Boost 1.71.0). Note that I've now also phased out Boost.FileSystem in lieu of `<filesystem>`.

**Closed as completed by rhalbersma** 2020-01-09 20:56 UTC
